blank_issues_enabled: true
contact_links:
  - name: Community forum
    url: https://forum.onlyoffice.com/
    about: The official ONLYOFFICE forum where you can post any questions or feedback.
  - name: Support request
    url: https://www.onlyoffice.com/support-contact-form.aspx
    about: If you have a valid license, please submit a request here to receive advanced support.
