name: "Feature request"
description: "Use this form to suggest a feature."
body:
  - type: checkboxes
    id: acknowledge
    attributes:
      label: "I acknowledge that:"
      options:
      - label: "I have used the [search tool](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues?q=) and did not find an issue describing my idea."
        required: true
      - label: "I have the latest versions of both the Document Server and the connector, and the feature I'm about to request is missing there."
        required: true
  - type: textarea
    attributes:
      label: Your idea.
    validations:
      required: true
